version: '3.5'
services:
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=Crediario
    ports:
      - "5432:5432"
    volumes:
      - postgres:/postgres
    expose:
      - 5432
    command: -p 5432
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8090
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres: